### ISSUE TITLE
Release for version 2 flutter

### ISSUE THREAD

**Issue by gaiousantonio0909** [mytooyo/board_datetime_picker#1]
I could contribute a version 2 compatible but if you have can make it public 😀 thanks

**Comment by mytooyo** [comment]
> I could contribute a version 2 compatible but if you have can make it public 😀 thanks

Thank you very much.
What kind of support are you considering for version 2?
I am considering making changes regarding focus and TextStyle in the time version.

**Comment by gaiousantonio0909** [comment]
I actually have a working version 2 of your great package :)
