### ISSUE TITLE
Editing of the fields is very difficult

### ISSUE THREAD

**Issue by matteoberla** [mytooyo/board_datetime_picker#12]
Hi, it seems that when editing the fields in order to choose a date, all the text fields acts in a strage way, not keeping the cursor on the selected position, numbers inserted are overridden before completing the entry, and so it's almost impossible to edit those fields manually.

Maybe a debounce on the inserted value would help.
If the inserted values are not acceptable then override them, but wait for the insertion to finish.

**Comment by mytooyo** [comment]
OK, correct the input control.

**Comment by matteoberla** [comment]
Ok, let me know if you found out a solution for it, thank you.

**Comment by mytooyo** [comment]
@matteoberla 
Improved input issues in v1.3.1 to allow for flexibility.   
If the input value is not acceptable, it will be corrected when it is out of focus.  
Please try it and let me know if you feel it needs more modification.

We also released another issue in v1.3.1

**Comment by matteoberla** [comment]
That is perfect, the red animation when the field is invalid was a brilliant idea.
Thank you very much for helping me.

**Comment by mytooyo** [comment]
@matteoberla 
Thank you very much.
You have helped us to improve the quality.
Please let me know if there is anything else I can do!
