### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by matteoberla** [mytooyo/board_datetime_picker#14]
Hi, i would like to show you some enhancements about the UI, let me know what you think and if my ideas are valid.
![duration picker](https://github.com/mytooyo/board_datetime_picker/assets/69200334/7bfa1d58-92bd-458c-bd0b-e86716b4371e)

-Title: Maybe a description of the picker to show what the user is doing could be useful in many situations.
-Adding the possibility of hiding the rectangle that usually contains "Today" "Tomorrow" as in many situations it's empty and it seems wrong.
-Move the confirm button and make it bigger: maybe in the top right corner as it is now but outside the rectangle
-Adding a custom (or fixed texts so they'll need to be translated) on the top of the picker to show if it's the day, month, year, hour, minute picker (Don't know if it's useful but i would use it).

Thank you.

**Comment by mytooyo** [comment]
Thanks for the idea!
It might be useful to have a flexible customizable feature that provides only the picker portion.
Indeed, I think that the UI needs to be improved, since the upper frame is no longer needed for `time` only.
Consider allowing the title and item name to be specified.

Is there a case where the "Today" or "Tomorrow" button is unnecessary even for a date/time picker?
I always display them for date/time pickers, but if they are not necessary in some cases, I need to consider hiding them.

**Comment by matteoberla** [comment]
when the time picker is shown there's only the empty white rectangle, also when minDate and maxDate are set and between them there's not today or tomorrow it has the same behaviour.

**Comment by mytooyo** [comment]
@matteoberla 
How about this kind of UI?

- Titled and subtitled as before with headers
<img width="1119" alt="first" src="https://github.com/mytooyo/board_datetime_picker/assets/25701661/667fa01b-87d2-4b7d-8eef-4f882af134cf">

- Title and subtitle without header (new UI)
<img width="1118" alt="second" src="https://github.com/mytooyo/board_datetime_picker/assets/25701661/63880fc2-fc9c-49c2-b724-df7b92fb7403">

- New UI for time only
<img width="1118" alt="third" src="https://github.com/mytooyo/board_datetime_picker/assets/25701661/391aef57-735f-4636-b13d-8d5ef552a676">

**Comment by matteoberla** [comment]
This seems to be much more clear.
Is the picker text customizable or fixed?
If fixed thse are the italian translations:
Year - Anno
Month - Mese
Day- Giorno
Hour - Ora
Minute- Minuto

**Comment by mytooyo** [comment]
It is implemented so that both title and subtitle can be specified.  
If there is not enough to display, the default English will be used to compensate.

```dart
class BoardDateTimeItemTitles {
  final String? year;
  final String? month;
  final String? day;
  final String? hour;
  final String? minute;

}
```

**Comment by matteoberla** [comment]
That's clear, thank you very much, you're doing an amazing job.
