### ISSUE TITLE
BoardDateTimeInputField shows keyboard

### ISSUE THREAD

**Issue by ames1982** [mytooyo/board_datetime_picker#26]
When using BoardDateTimeInputField and u tap on the text field the keyboard appears over the date selection tools, hiding keyboard then hides date selection tools, its not usable

**Comment by mytooyo** [comment]
> When using BoardDateTimeInputField and u tap on the text field the keyboard appears over the date selection tools, hiding keyboard then hides date selection tools, its not usable

If you do not need the Picker, set it to `showPicker: false` once.
If you need the Picker even when the keyboard is displayed, there is no effective way to do this at this time.
Please wait until we fix it.

**Comment by mytooyo** [comment]
@ames1982 
Please check the fix in v1.6.5
