### ISSUE TITLE
New feature - mini calendar view

### ISSUE THREAD

**Issue by matteoberla** [mytooyo/board_datetime_picker#29]
Hi, i was thining that instead of showing the bottomModalSheet it could be useful in some cases to show only a small calendar popup with a textfield for selecting the date (i think that on web would be more space saving and more user friendly, maybe it could be useful also for someone that wants to show it on mobile).
the concept would be this:
![Immagine](https://github.com/mytooyo/board_datetime_picker/assets/69200334/06e0d305-1508-4984-9b77-c9c91c0136c2)

Do you think is a valid idea?
Thank you in advance

**Comment by matteoberla** [comment]
idk if it could be useful but this is what i expect to happen, instead of the container the mini calendar view should be showed.
Of course the key would be necessary in this case to be passed, idk if there's a better way to do it.

```
ElevatedButton(
            key: key,
            child: const Text("test"),
            onPressed: () {
              RenderBox box =
                  key.currentContext?.findRenderObject() as RenderBox;
              Offset position =
                  box.localToGlobal(Offset.zero); //this is global position

              Size? sizes = key.currentContext?.size;

              double y = position.dy + (sizes?.height ?? 0);
              double x = position.dx;

              showDialog(
                barrierColor: transparent,
                context: context,
                builder: (BuildContext context) {
                  return Stack(
                    children: [
                      Positioned(
                        top: y,
                        left: x,
                        child: Container(
                          width: 300,
                          height: 300,
                          color: backgroundColor,
                        ),
                      ),
                    ],
                  );
                },
              );
            },
          ),
```

**Comment by mytooyo** [comment]
Thank you for the feature suggestion.
Using `showDialog` would make it difficult to coexist with input fields. In addition, it would be difficult to display a calendar on a mobile device due to the software keyboard.
I will give some consideration to implementation.

**Comment by matteoberla** [comment]
I was thinking more about a web implementation for now, but if you can find a solution for mobile too it would be very nice. Thank you very much

**Comment by matteoberla** [comment]
find a similar end result even if many things are missing, hope it can help
https://pub.dev/packages/vph_web_date_picker

**Comment by mytooyo** [comment]
Thank you very much.
The current implementation makes it difficult to add these features.
I will look into how to implement this when I can find the time.

**Comment by mytooyo** [comment]
@matteoberla 

I have been able to implement a form that uses the current Picker. I am not able to change the calendar notation, etc. because it would be different from this package.
Added `showPickerType` parameter to the `BoardDateTimeInputField` class. By specifying `BoardDateTimeFieldPickerType.mini`, you can make the UI look like the attached

https://github.com/mytooyo/board_datetime_picker/assets/25701661/07c64953-1f4c-44e9-ad08-bd1f70880503

**Comment by matteoberla** [comment]
Thank you very much, I'll try it tomorrow and let you know

**Comment by matteoberla** [comment]
Everything works fine.
Thank you very much!
