### ISSUE TITLE
Italian language (and other european languages) support

### ISSUE THREAD

**Issue by matteoberla** [mytooyo/board_datetime_picker#3]
Are other languages other than en() and ja() supported? I can't find other languages inside the package.

**Comment by mytooyo** [comment]
> Are other languages other than en() and ja() supported? I can't find other languages inside the package.

Only English and Japanese are defined in the package, but they can be specified as options.
Since it is difficult to cover all languages, it is recommended to specify them as follows.
Or, would you prefer to have the definitions in the package?

```dart
import 'package:board_datetime_picker/board_datetime_picker.dart';
import 'package:flutter/material.dart';

class SampleApp extends StatefulWidget {
  const SampleApp({super.key});

  @override
  State<SampleApp> createState() => _SampleAppState();
}

class _SampleAppState extends State<SampleApp> {
  final controller = BoardDateTimeController();

  DateTime date = DateTime.now();

  @override
  Widget build(BuildContext context) {
    final languages = BoardPickerLanguages(
      weekdays: ['dom.', 'lun.', 'mar.', 'merc.', 'gio.', 'ven.', 'sab.'],
      today: 'Oggi',
      tomorrow: 'Domani',
      now: 'il corrente',
    );

    final options = BoardDateTimeOptions(
      languages: languages,
    );

    return BoardDateTimeBuilder(
      builder: (context) {
        return Scaffold(
          body: Center(
            child: ElevatedButton(
              child: Text(
                BoardDateFormat('yyyy/MM/dd').format(date),
              ),
              onPressed: () {
                controller.openPicker();
              },
            ),
          ),
        );
      },
      options: options,
      controller: controller,
      onChange: (val) {
        setState(() => date = val);
      },
    );
  }
}

```

**Comment by matteoberla** [comment]
If you want you can send me all the texts, (weekdays, months, and other
texts used in the package) and I’ll translate at least in Italian so you
can include it. Thanks

Il giorno sab 28 ott 2023 alle 06:18 mytooyo ***@***.***> ha
scritto:

**Comment by mytooyo** [comment]
Thank you.
Now, could you please tell us about the following items so that we can support Italian and other European languages?

- `weekdays`
- `today`
- `tomorrow`
- `now`

Please provide any other items you need.

**Comment by matteoberla** [comment]
- weekdays - giorni della settimana
   - today - oggi
   - tomorrow - domani
   - now - adesso


Monday - sunday:
Lunedì
Martedì
Mercoledì
Giovedì
Venerdì
Sabato
Domenica

Jan-Dec:
Gennaio
Febbraio
Marzo
Aprile
Maggio
Giugno
Luglio
Agosto
Settembre
Ottobre
Novembre
Dicembre

Il giorno sab 28 ott 2023 alle 14:12 mytooyo ***@***.***> ha
scritto:

**Comment by mytooyo** [comment]
Thank you.
Is there a shortened form of Monday - Sunday?

**Comment by mytooyo** [comment]
Language can now be changed by putting a setting for Italian in the options `languages`.

```dart
options: BoardDateTimeOptions(
  languages: const BoardPickerLanguages.it(),
),
```

**Comment by matteoberla** [comment]
You can write
Lun Mar Mer Gio Ven Sab Dom

Or write only the first letter of each day even if the second and third
start with the same.

Il giorno dom 29 ott 2023 alle 02:37 mytooyo ***@***.***> ha
scritto:

**Comment by matteoberla** [comment]
Thank you very much for supporting Italian as new language. I appreciate it
a lot

Il giorno dom 29 ott 2023 alle 05:38 mytooyo ***@***.***> ha
scritto:

**Comment by mytooyo** [comment]
It is supported in v1.2.1, so please try it.

**Comment by matteoberla** [comment]
I’ll test it tomorrow morning, thank you very much.

Il giorno dom 29 ott 2023 alle 13:11 mytooyo ***@***.***> ha
scritto:

**Comment by matteoberla** [comment]
It seems to be working fine, i'll open another issue with some bugs found as i need some more explaination
