### ISSUE TITLE
Keyboard appears when accidentally pressing a date value in the slider

### ISSUE THREAD

**Issue by Jamerze** [mytooyo/board_datetime_picker#31]
![Screenshot_20240531_101610](https://github.com/mytooyo/board_datetime_picker/assets/70536433/3f4b6417-3a6b-42be-b493-651239b54399)

Hello, while using the slider widget of this plugin, I accidentally pressed on the month field and noticed that my keyboard appeared which made me able to edit the field and enter (e.g.) 56. This is also possible for the day and year field.
I couldn't localize it in the code, but is there a way to disable this and prevent the keyboard from opening?

Furthermore, the calendar works really well and is great to use. Thanks for providing this plugin :)

**Comment by mytooyo** [comment]
@Jamerze 
Thank you for the feedback!

Am I correct in saying that the keyboard should not appear when I tap on the selected date in the center of the picker?
(Is this a mode that does not require keyboard input?)

**Comment by Jamerze** [comment]
@mytooyo 
Hi, thank you for the quick response. I just realized this is actually a feature and not a bug to quickly set the day, month or year in the slider so that you not always have to scroll. 
But in our case we'd indeed like to prevent the keyboard from appearing and would like to only use the slider functionality (so no keyboard input) if possible.

**Comment by mytooyo** [comment]
Yes. I have implemented the ability to enter text as well as scroll.
I think that there are cases where you may want to use only a simple Picker, so I will add an option.

**Comment by mytooyo** [comment]
Added `inputable` option.
Setting it to `false` will prevent the keyboard from being displayed.

```dart
options: BoardDateTimeOptions(
  inputable: false,
)
```

Please try v1.6.6.

**Comment by Jamerze** [comment]
@mytooyo 
Thanks! Works really well.
