### ISSUE TITLE
Hiding day-month-year selectors

### ISSUE THREAD

**Issue by matteoberla** [mytooyo/board_datetime_picker#35]
Hi, 
when using bottomsheet picker with `DateTimePickerType.dateTime` in some tablet screen the elements are shrinked and it is difficult to use the selectors.

Here is what happens: 
![Immagine 2024-06-10 111052](https://github.com/mytooyo/board_datetime_picker/assets/69200334/646d804a-56a6-496f-8b0d-a86649a8d4ab)

It would be nice to have the possibility to hide the day-month-year selectors as the calendar is already enough in order to select the desired date.

I think that it would be better to add another `DateTimePickerType` so users that will use this package will be able to choose between different layout and programmatically choose which one is the better based on the screen size, or just add a voice inside the options to hide the dd/mm/yyyy selectors.

Is it possibile? Thank you very much

**Comment by mytooyo** [comment]
The `breakpoint` parameter can be used to adjust the split display.
Currently, this package is mainly for Picker with wheel selection.   
Therefore, it is not intended to be a calendar-only display.  

There are no plans to implement voice input at this time, given the level of difficulty and other factors.

**Comment by matteoberla** [comment]
Maybe i explained wrong what i was trying to achiving.

here's the result i would like to reach, just for UX purpose.

![Immagine 2024-06-10 111052](https://github.com/mytooyo/board_datetime_picker/assets/69200334/46c2a545-1058-4cee-a9ee-977a3b73c6fe)

>  or just add a voice inside the options to hide the dd/mm/yyyy selectors
I meant adding a property true/false to hide or show the year - month - day selectors from the bottom sheet

**Comment by matteoberla** [comment]
Cannot it be a new type of `DateTimePickerType` as it allows users to both select date and time but in a more shrinked way?

**Comment by mytooyo** [comment]
If I can achieve the same UX in a narrow window, I may add a type, but I can't think of a good idea at the moment.
I'd like to avoid adding type just for wide windows.

**Comment by matteoberla** [comment]
ok that's clear, do you have by any chance any other workaround to show the calendar and the time picker in the same view?

I would like that the final user can select both date and time from the same view without interacting with other buttons as it could be not that intuitive for an unexpert user

**Comment by mytooyo** [comment]
No other features other than those currently offered.
