### ISSUE TITLE
Break when building

### ISSUE THREAD

**Issue by Xebache** [mytooyo/board_datetime_picker#39]
Hi there,

I really like your date picker. Unfortunately, it is broken when trying to build and deploy... Works fine in debug.
I even tried to build and deploy your example, thinking i was doing something bad, the result is a gray screen...
Any idea ?

**Comment by mytooyo** [comment]
@Xebache 
Thank you for the feedback.
A bug was found that caused type checking to fail in Web release mode. Fix type checking to be done only in debug mode.
