### ISSUE TITLE
Board datetime picker as classic widget

### ISSUE THREAD

**Issue by matteoberla** [mytooyo/board_datetime_picker#4]
The BoardDatetimePickerBuilder is hard to be integrated into an existing page, it needs to be wrapped around the entire page, furthermore if i have many datepickers it's not that immediate to use as i need to map which picker was selected and then get the value and assign to that selected picker.

Wouldn't a classic widget be easier to use? For example a button that when pressed opens a modal bottom sheet with the calendar/pickers and a callback function that returns the value selected as other packages do, that can be found on pub.dev

**Comment by mytooyo** [comment]
Thank you very much.
You are right, it would be useful to have a use like a modal bottom sheet. 
I will consider implementing it.

**Comment by mytooyo** [comment]
@matteoberla 
I have added the ability to display the picker in bottom_moda_sheet in version `1.2.0`.

Best regards.

**Comment by matteoberla** [comment]
Thank you very much, I’ll test it on Monday.

Il giorno sab 28 ott 2023 alle 08:33 mytooyo ***@***.***> ha
scritto:
