### ISSUE TITLE
New feature- support select second under the time type

### ISSUE THREAD

**Issue by shingohu** [mytooyo/board_datetime_picker#41]
RT

**Comment by mytooyo** [comment]
> RT

Is this feature to display/select seconds only for time type?

**Comment by shingohu** [comment]
> > RT
> 
> Is this feature to display/select seconds only for time type?

yes

**Comment by mytooyo** [comment]
@shingohu 
Hi! I added the feature to select seconds in 2.1.0.
Add an option that is only valid if `DateTimePickerType.time` is specified. It will work if you specify the parameters as follows.

```dart
showBoardDateTimePicker(
  context: context,
  pickerType: DateTimePickerType.time,
  options: BoardDateTimeOptions(
    withSecond: true, // <- added option
  ),
);
```
