### ISSUE TITLE
bug - onFocusChanged not called

### ISSUE THREAD

**Issue by matteoberla** [mytooyo/board_datetime_picker#50]
hi, i've noticed that `onFocusChange` is not called sometimes on web when exiting from the field.

-When pressing Enter to unfocus the field
-Once you press outside the field to unfocus it, but i see that the autocompleting is working

I've noticed also that by pressing inside and outside (without making any change to the date) the focus change is called correctly.

Here's a console log
As you can see,
`on focus changed date: FALSE` is missing
![errore board](https://github.com/user-attachments/assets/8f752219-4954-4966-aac4-864986111a6b)

**Comment by matteoberla** [comment]
Doing some more research,
if i select the text without focusing the field,
`onFocusChange -> true` IS called, when unfocusing it  `onFocusChange -> false` IS NOT called

if i press inside the field, then i select the text,
`onFocusChange -> true` IS called, when unfocusing it  `onFocusChange -> true` IS called

**Comment by tiltmaster** [comment]
indeed this is an issue, a disappointing one, was so hyped for a second.

**Comment by mytooyo** [comment]
@matteoberla 
Thanks for the research.

> if i select the text without focusing the field,

What is the procedure for this?
In my environment, it seems that the callback is invoked even if the selection is made with the tab key, etc.
When unfocusing with Enter key or tapping outside, onFocusChanged is called in both cases

**Comment by matteoberla** [comment]
-Start with nothing focused
-Try to select the text until it's all highlighted (don't tap inside the field, just select the text directly)
-Make some changes to the text value
-Exit from the field by tapping outside

Hope you will be able to reproduce this, otherwise I'll make a short video

Thank you.

**Comment by mytooyo** [comment]
> -Start with nothing focused -Try to select the text until it's all highlighted (don't tap inside the field, just select the text directly) -Make some changes to the text value -Exit from the field by tapping outside
> 
> Hope you will be able to reproduce this, otherwise I'll make a short video
> 
> Thank you.

I found out how to reproduce it. Thank you.

**Comment by mytooyo** [comment]
Released in v2.1.4

**Comment by matteoberla** [comment]
Thank you very much
