### ISSUE TITLE
../../.pub-cache/hosted/pub.dev/board_datetime_picker-2.2.0/lib/src/ui/parts/header.dart:169:39: Error: The method 'withValues' isn't defined for the class 'Color'.

### ISSUE THREAD

**Issue by BriscoPeas93** [mytooyo/board_datetime_picker#56]
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/board_datetime_picker-2.2.0/lib/src/ui/parts/header.dart:169:39: Error: The method 'withValues' isn't defined for the class 'Color'.

Could not build the application for the simulator.
Error launching application on iPhone 16 Plus.

**Comment by mytooyo** [comment]
@BriscoPeas93 

Version 2.2.0 is optimized for Flutter 3.27. If your Flutter version is below that, please stick to version 2.1.6.

**Comment by BriscoPeas93** [comment]
Thanks.
It's working fine with the update(Flutter 3.27)
